name: mnist_flutter
description: "A new Flutter project."
publish_to: 'none' # Prevent publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.7    # Untuk memilih gambar dari galeri
  image: ^4.1.4           # Untuk memproses gambar
  path_provider: ^2.1.1   # Untuk menyimpan riwayat
  shared_preferences: ^2.2.2 # Untuk penyimpanan lokal
  tflite_flutter: ^0.11.0  # Untuk menjalankan model TFLite
  ffi: ^2.0.2   # Dibutuhkan untuk binding TFLite ke Flutter

  cupertino_icons: ^1.0.8 # Untuk icon iOS

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Untuk memastikan best practices dalam coding

flutter:
  uses-material-design: true

  assets:
    - assets/digits_model.tflite
    - assets/letters_model.tflite
